name: Docker Meta
description: GitHub Action to extract metadata (tags, labels) for Docker
author: itsmycargo
branding:
  color: blue
  icon: layers

inputs:
  repository:
    description: Docker repository where image is to be published
    required: true
  github-token:
    description: GitHub Token as provided by secrets
    default: ${{ github.token }}
    required: true
  release-managed:
    description: Whether Github releases are used for tagging
    default: "false"
    required: false

outputs:
  repositoryTag:
    description: Generated full image:tag format of published image
  repository:
    description: Full URL of Published Image
  tag:
    description: Generated Main Docker Tag for Commit
  tags:
    description: Generated Docker tags
  labels:
    description: Generated Docker labels

runs:
  using: node12
  main: index.js
